version: '3'

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-llm-{llm_id}
    ports:
      - "{port}:25565"
      - "{rcon_port}:25575"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MODE: "creative"
      MEMORY: "2G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "{rcon_password}"
      RCON_PORT: "25575"
      ONLINE_MODE: "false"
      # Optimized JVM flags for better performance
      JVM_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "2G"
      # Optimize view distance
      VIEW_DISTANCE: "8"
      # Enable healthchecks
      ENABLE_HEALTHCHECK: "true"
    volumes:
      - "mc-data-{llm_id}:/data"
    tty: true
    stdin_open: true
    restart: "unless-stopped"
    healthcheck:
      test: mc-health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m

volumes:
  mc-data-{llm_id}:
